server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://monitoring.kokomen.kr:3100/loki/api/v1/push

scrape_configs:
  - job_name: kokomen-app-prod
    static_configs:
      - labels:
          job: kokomen-app
          app: kokomen
          host: ${HOSTNAME}
          __path__: /logs/app/app.log
