language: "ko-KR"
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    base_branches:
      - "develop"
      - "main"
  tools:
    detekt:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    actionlint:
      enabled: true
    hadolint:
      enabled: true
    checkov:
      enabled: true
chat:
  auto_reply: true
