services:
  test-mysql:
    image: mysql:8.4.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kokomen-test
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_INIT_CONNECT: "SET NAMES utf8mb4"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci"
      ]
    ports:
      - 13306:3306
