api:
  dashboard: false

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: api_api-net
    watch: true

accessLog:
  format: json
  fields:
    headers:
      names:
        X-Real-IP: keep
        X-Request-ID: keep

log:
  level: INFO
  format: json
