spring:
  jpa:
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
server:
  servlet:
    session:
      timeout: 24h
      cookie:
        name: JSESSIONID
        path: /
        secure: true
        http-only: true
        same-site: lax
        max-age: 86400
open-ai:
  api-key: ${OPEN_AI_API_KEY}

management:
  endpoint:
    health:
      show-components: always
      access: read_only
    info:
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: prometheus, info, health, metrics

---
# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://kokomen-mysql:3306/kokomen-local
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://localhost:8080/login/callback
    client-secret: ${KAKAO_CLIENT_SECRET}
  frontend-uri: http://localhost:8080
cors:
  allowed-origins: http://localhost:8080

---
# dev profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID_DEV}
    redirect-uri: https://kokomen.kr/login/callback
    client-secret: ${KAKAO_CLIENT_SECRET_DEV}
  frontend-uri: https://kokomen.kr
cors:
  allowed-origins: http://localhost:3000, https://kokomen.kr, https://www.kokomen.kr
