spring:
  jpa:
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
open-ai:
  api-key: ${OPEN_AI_API_KEY}

management:
  endpoint:
    health:
      show-components: always
      access: read_only
    info:
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: prometheus, info, health, metrics

---
# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://kokomen-mysql:3306/kokomen-local
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://localhost:8080/api/v1/auth/kakao-login/redirect
    client-secret: ${KAKAO_CLIENT_SECRET}
  frontend-uri: http://localhost:8080
cors:
  allowed-origins: http://localhost:8080

---
# dev profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID_DEV}
    redirect-uri: https://api-dev.kokomen.kr/api/v1/auth/kakao-login/redirect
    client-secret: ${KAKAO_CLIENT_SECRET_DEV}
  frontend-uri: https://kokomen.kr
cors:
  allowed-origins: http://localhost:3000, https://kokomen.kr, https://www.kokomen.kr
