oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID_DEV}
    client-secret: ${KAKAO_CLIENT_SECRET_DEV}
    admin-key: ${KAKAO_ADMIN_KEY_DEV}
  google:
    client-id: ${GOOGLE_CLIENT_ID_DEV}
    client-secret: ${GOOGLE_CLIENT_SECRET_DEV}
cors:
  allowed-origins: https://dev.kokomen.kr, https://kokomen.kr:3000, https://local.kokomen.kr:3000, http://local.kokomen.kr:3000, https://www.webview-dev.kokomen.kr, https://webview-dev.kokomen.kr
server:
  servlet:
    session:
      cookie:
        domain: kokomen.kr
        secure: false
aws:
  root-question-s3-path: dev/root-question-voice/
  next-question-s3-path: dev/next-question-voice/
  resume-s3-path: dev/resume/
  portfolio-s3-path: dev/portfolio/
  company-s3-path: recruit/dev/company/
tosspayments:
  widget-secret-key: ${WIDGET_SECRET_KEY_DEV}
retry:
  tosspayments:
    max-attempts: 3
    initial-interval: 500
    multiplier: 2.0
    max-interval: 2000
