spring:
  jpa:
    open-in-view: false
open-ai:
  api-key: ${OPEN_AI_API_KEY}

---
# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://kokomen-mysql:3306/kokomen-local
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop


---
# dev profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
