oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID_PROD}
    client-secret: ${KAKAO_CLIENT_SECRET_PROD}
    admin-key: ${KAKAO_ADMIN_KEY_PROD}
  google:
    client-id: ${GOOGLE_CLIENT_ID_PROD}
    client-secret: ${GOOGLE_CLIENT_SECRET_PROD}
cors:
  allowed-origins: https://kokomen.kr, https://www.kokomen.kr, https://www.webview.kokomen.kr, https://webview.kokomen.kr
server:
  servlet:
    session:
      cookie:
        domain: kokomen.kr
        secure: true
aws:
  root-question-s3-path: dev/root-question-voice/
  next-question-s3-path: dev/next-question-voice/
  resume-s3-path: dev/resume/
  portfolio-s3-path: dev/portfolio/
  company-s3-path: recruit/dev/company/
tosspayments:
  widget-secret-key: ${WIDGET_SECRET_KEY_PROD}
retry:
  tosspayments:
    max-attempts: 3
    initial-interval: 500
    multiplier: 2.0
    max-interval: 2000
