spring:
  jpa:
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
  session:
    store-type: redis
server:
  servlet:
    session:
      timeout: 24h
      cookie:
        name: JSESSIONID
        path: /
        secure: true
        http-only: true
        same-site: lax
        max-age: 86400
open-ai:
  api-key: ${OPEN_AI_API_KEY}
management:
  server:
    port: 8081
    address: 0.0.0.0
  endpoint:
    health:
      show-components: always
      access: read_only
    info:
      access: read_only
    metrics:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    web:
      exposure:
        include: prometheus, info, health, metrics

---
# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://kokomen-mysql:3306/kokomen-local
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: kokomen-redis
      port: 6379
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
cors:
  allowed-origins: http://localhost:8080

---
# dev profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL_DEV}
    username: ${SPRING_DATASOURCE_USERNAME_DEV}
    password: ${SPRING_DATASOURCE_PASSWORD_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: kokomen-redis-dev
      port: 6379
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID_DEV}
    client-secret: ${KAKAO_CLIENT_SECRET_DEV}
cors:
  allowed-origins: http://localhost:3000, https://kokomen.kr, https://www.kokomen.kr, https://kokomen.kr:3000 # TODO: 개발환경 uri로 변경
server:
  servlet:
    session:
      cookie:
        domain: kokomen.kr

---
# prod profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL_PROD}
    username: ${SPRING_DATASOURCE_USERNAME_PROD}
    password: ${SPRING_DATASOURCE_PASSWORD_PROD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_CLUSTER_ENDPOINT}
      port: 6379
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID_PROD}
    client-secret: ${KAKAO_CLIENT_SECRET_PROD}
cors:
  allowed-origins: https://kokomen.kr, https://www.kokomen.kr
server:
  servlet:
    session:
      cookie:
        domain: kokomen.kr
