spring:
  application:
    name: kokomen-interview-consumer
  profiles:
    include:
      - common
  datasource:
    hikari:
      maximum-pool-size: 6
      minimum-idle: 6
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  kafka:
    consumer:
      group-id: default-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    properties:
      security.protocol: PLAINTEXT
server:
  tomcat:
    threads:
      min-spare: 1
      max: 2
    max-connections: 10
    accept-count: 5
management:
  server:
    port: 8081
    address: 0.0.0.0

---
# local profile
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: kokomen-local-kafka:9092
    streams:
      bootstrap-servers: kokomen-local-kafka:9092
      application-id: interview-like-streams

---
# dev profile
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    streams:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      application-id: interview-like-streams
---

# prod profile
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    streams:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      application-id: interview-like-streams

---
# load-test profile
spring:
  config:
    activate:
      on-profile: load-test
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    streams:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      application-id: interview-like-streams
