ALTER TABLE root_question
    MODIFY COLUMN category ENUM(
    'ALGORITHM',
    'DATA_STRUCTURE',
    'ALGORITHM_DATA_STRUCTURE',
    'DATABASE',
    'NETWORK',
    'OPERATING_SYSTEM',
    'JAVA_SPRING',
    'INFRA',
    'FRONTEND',
    'REACT',
    'JAVASCRIPT_TYPESCRIPT'
    ) NOT NULL;

UPDATE root_question
SET category = 'ALGORITHM_DATA_STRUCTURE'
WHERE category IN ('ALGORITHM', 'DATA_STRUCTURE');

ALTER TABLE root_question
    MODIFY COLUMN category ENUM(
    'ALGORITHM_DATA_STRUCTURE',
    'DATABASE',
    'NETWORK',
    'OPERATING_SYSTEM',
    'JAVA_SPRING',
    'INFRA',
    'FRONTEND',
    'REACT',
    'JAVASCRIPT_TYPESCRIPT'
    ) NOT NULL;
