server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.37.94:3100/loki/api/v1/push

scrape_configs:
  - job_name: kokomen-app-load-test
    static_configs:
      - labels:
          job: kokomen-app-load-test
          app: kokomen
          host: ${HOSTNAME}
          __path__: /logs/app/app.log
    pipeline_stages:
      - regex:
          expression: '\[.*?\] [\d\-:.\s]+ \[.*?\] (?P<level>[A-Z]+)\s'
      - labels:
          level:
