server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: interview-api-dev
    static_configs:
      - labels:
          job: interview-api
          app: interview-api
          host: ${HOSTNAME}
          __path__: /logs/interviews/api/app.log
    pipeline_stages:
      - multiline:
          firstline: '^\[[^\]]+\]\s\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3}\s[^\[]+\s\[[^\]]+\]'
      - regex:
          expression: '\[.*?\] [\d\-:.\s]+ [^\[\]]+ \[.*?\]\s+(?P<level>[A-Z]+)\s+[^\s]+'
      - labels:
          level:
  - job_name: interview-consumer-dev
    static_configs:
      - labels:
          job: interview-consumer
          app: interview-consumer
          host: ${HOSTNAME}
          __path__: /logs/interviews/consumer/app.log
    pipeline_stages:
      - multiline:
          firstline: '^\[[^\]]+\]\s\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3}\s[^\[]+\s\[[^\]]+\]'
      - regex:
          expression: '\[.*?\] [\d\-:.\s]+ [^\[\]]+ \[.*?\]\s+(?P<level>[A-Z]+)\s+[^\s]+'
      - labels:
          level:
