positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: kokomen-app-dev
    static_configs:
      - labels:
          job: kokomen-app
          __path__: /logs/app/app.log
    pipeline_stages:
      - json:
          expressions:
            app: app
            host: host
            level: level
            timestamp: timestamp
            logger: logger
            thread: thread
            message: message
      - labels:
          app:
          host:
          level:
      - template:
          source: enhanced_message
          template: |
            [{{.timestamp}}] [{{.logger}}] [{{.thread}}] {{.message}}
      - output:
          source: enhanced_message
