name: CD DEV

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Sign in Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -f ./Dockerfile --platform linux/amd64 --no-cache -t samhap/kokomen:dev .

      - name: Push the Docker Image to Dockerhub
        run: docker push samhap/kokomen:dev

  deploy:
    needs: build
    runs-on: [self-hosted, dev]

    steps:
      - name: Docker Image pull
        run: sudo docker pull samhap/kokomen:dev

      - name: Stop existing container
        run: |
          sudo docker ps -q --filter "ancestor=samhap/kokomen:dev" | xargs -r docker stop
          sudo docker ps -a -q --filter "ancestor=samhap/kokomen:dev" | xargs -r docker rm
      
      - name: Docker run
        run: |
          sudo docker run --rm -e SPRING_PROFILES_ACTIVE=dev \
            -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL_DEV }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD_DEV }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME_DEV }} \
            -p 80:8080 -d samhap/kokomen:dev
