name: CD DEV

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant execute permission for run-test-mysql.sh
        run: chmod +x run-test-mysql.sh

      - name: Start MySQL for testing
        run: ./run-test-mysql.sh

      - name: Build with Gradle
        run: ./gradlew build

      - name: Sign in Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -f ./Dockerfile --platform linux/amd64 --no-cache -t samhap/kokomen:dev .

      - name: Push the Docker Image to Dockerhub
        run: docker push samhap/kokomen:dev

  deploy:
    needs: build
    runs-on: [ self-hosted, dev ]

    steps:
      - name: Docker Image pull
        run: sudo docker pull samhap/kokomen:dev

      - name: Stop existing container
        run: sudo docker rm -f kokomen-dev-server

      - name: Docker Image prune
        run: sudo docker image prune -f -a

      - name: pull docker compose yaml files
        working-directory: /home/ubuntu
        run: |
          [ -d kokomen-backend ] || git clone --filter=blob:none --no-checkout https://github.com/samhap-soft/kokomen-backend.git
          cd kokomen-backend
          git sparse-checkout init --cone
          git checkout develop
          git sparse-checkout set docker
          git pull origin develop

      - name: Docker run
        working-directory: /home/ubuntu
        env:
          SPRING_DATASOURCE_URL_DEV: ${{ secrets.SPRING_DATASOURCE_URL_DEV }}
          SPRING_DATASOURCE_USERNAME_DEV: ${{ secrets.SPRING_DATASOURCE_USERNAME_DEV }}
          SPRING_DATASOURCE_PASSWORD_DEV: ${{ secrets.SPRING_DATASOURCE_PASSWORD_DEV }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          KAKAO_CLIENT_ID_DEV: ${{ secrets.KAKAO_CLIENT_ID_DEV }}
          KAKAO_CLIENT_SECRET_DEV: ${{ secrets.KAKAO_CLIENT_SECRET_DEV }}
          MYSQL_ROOT_PASSWORD_DEV: ${{ secrets.MYSQL_ROOT_PASSWORD_DEV }}
        run: |
          export HOSTNAME=$(hostname)
          cd kokomen-backend/docker/dev
          sudo -E docker compose -f docker-compose-dev.yml up -d
