name: CD PROD

#on:
#  push:
#    branches: [ main ]
on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant execute permission for run-test-mysql.sh
        run: chmod +x run-test-mysql.sh

      - name: Start MySQL for testing
        run: ./run-test-mysql.sh

      - name: Build with Gradle
        run: ./gradlew build

      - name: Sign in Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -f ./Dockerfile --platform linux/arm64 --no-cache -t samhap/kokomen:prod .

      - name: Push the Docker Image to Dockerhub
        run: docker push samhap/kokomen:prod

  deploy:
    needs: build
    runs-on: [ self-hosted, prod ]

    strategy:
      matrix:
        runner: [ prod-a, prod-b ]

    steps:
      - name: Docker Image pull
        run: sudo docker pull samhap/kokomen:prod

      - name: Stop existing container
        run: sudo docker rm -f kokomen-prod-server

      - name: Docker Image prune
        run: sudo docker image prune -f -a

      #      - name: pull docker compose yaml files
      #        working-directory: /home/ubuntu
      #        run: |
      #          [ -d kokomen-backend ] || git clone --filter=blob:none --no-checkout https://github.com/samhap-soft/kokomen-backend.git
      #          cd kokomen-backend
      #          git sparse-checkout init --cone
      #          git fetch origin main
      #          git checkout main
      #          git sparse-checkout set docker
      #          git pull origin main
      - name: pull docker compose yaml files
        working-directory: /home/ubuntu
        run: |
          [ -d kokomen-backend ] || git clone --filter=blob:none --no-checkout https://github.com/samhap-soft/kokomen-backend.git
          cd kokomen-backend
          git sparse-checkout init --cone
          git fetch origin feature/#52
          git checkout feature/#52
          git sparse-checkout set docker
          git pull origin feature/#52

      - name: Docker run
        working-directory: /home/ubuntu
        env:
          SPRING_DATASOURCE_URL_PROD: ${{ secrets.SPRING_DATASOURCE_URL_PROD }}
          SPRING_DATASOURCE_USERNAME_PROD: ${{ secrets.SPRING_DATASOURCE_USERNAME_PROD }}
          SPRING_DATASOURCE_PASSWORD_PROD: ${{ secrets.SPRING_DATASOURCE_PASSWORD_PROD }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          KAKAO_CLIENT_ID_PROD: ${{ secrets.KAKAO_CLIENT_ID_PROD }}
          KAKAO_CLIENT_SECRET_PROD: ${{ secrets.KAKAO_CLIENT_SECRET_PROD }}
          MYSQL_ROOT_PASSWORD_PROD: ${{ secrets.MYSQL_ROOT_PASSWORD_PROD }}
          REDIS_CLUSTER_ENDPOINT: ${{ secrets.REDIS_CLUSTER_ENDPOINT }}
        run: |
          export HOSTNAME=$(hostname)
          cd kokomen-backend/docker/prod
          sudo -E docker compose -f docker-compose-prod.yml up -d
