name: CI TEST

on:
  pull_request:
    branches: [ main, release, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew build

      - name: When test fail, comment on that code
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: ${{ github.workspace }}/build/test-results/**/*.xml
          token: ${{ github.token }}
